apiVersion: apps/v1
kind: Deployment
metadata:
  name: spinnaker-dcd-controller
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    spec:
      containers:
        - name: controller
          image: spinnaker-dcd-controller
          imagePullPolicy: Never
          args:
            - --metrics-addr=0.0.0.0:8080
            - --enable-leader-election
            - --verbose
