apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spinnaker-dcd-controller
rules:
  - apiGroups:
      - spinnaker.kaidotdev.github.io
    resources:
      - applications
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - spinnaker.kaidotdev.github.io
    resources:
      - applications/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - spinnaker.kaidotdev.github.io
    resources:
      - pipelinetemplates
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - spinnaker.kaidotdev.github.io
    resources:
      - pipelinetemplates/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - spinnaker.kaidotdev.github.io
    resources:
      - pipelines
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - spinnaker.kaidotdev.github.io
    resources:
      - pipelines/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - patch
