apiVersion: apps/v1
kind: Deployment
metadata:
  name: spinnaker-dcd-controller
spec:
  selector:
    matchLabels:
      app: spinnaker-dcd-controller
  replicas: 1
  template:
    metadata:
      labels:
        app: spinnaker-dcd-controller
    spec:
      serviceAccountName: spinnaker-dcd-controller
      securityContext:
        sysctls:
          # https://github.com/kubernetes/kubernetes/pull/54896
          #- name: net.core.somaxconn
          #  value: "65535"
          - name: net.ipv4.ip_local_port_range
            value: "10000 65535"
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - spinnaker-dcd-controller
                topologyKey: kubernetes.io/hostname
              weight: 100
      containers:
        - name: controller
          image: docker.pkg.github.com/kaidotdev/spinnaker-dcd-controller/spinnaker-dcd-controller:dc45eaa
          imagePullPolicy: Always
          args:
            - --metrics-addr=0.0.0.0:8080
            - --enable-leader-election
          ports:
            - containerPort: 8080
