namespace: kube-system

resources:
  - crd/spinnaker.kaidotdev.github.io_applications.yaml
  # +kubebuilder:scaffold:crdkustomizeresource
  - cluster_role.yaml
  - cluster_role_binding.yaml
  - deployment.yaml
  - role.yaml
  - role_binding.yaml
  - service_account.yaml
